### ISSUE TITLE
Indexed properties in the Page Builder API 

### ISSUE THREAD

**Issue by dinhlongviolin1** [Avaiga/taipy-doc#845] opened 2024-02-27 15:03 UTC
**Description**
Index property can be defined directly within Page Builder API with double underscore
```python
# Wtih Markdown
page = """
<|{data}|chart|mode=lines|x=Date|y[1]=Temp°C|y[2]=Min|y[3]=Max|line[1]=dash|color[2]=blue|color[3]=red|>
"""

# With Taipy Gui Builder API
with tgb.Page() as tgb_page:
    tgb.chart("{data}", mode="lines", x="Date", y__1="Temp°C", y__2="Min", y__3="Max", line__1="dash",color__2="blue", color__3="red")
```

**Comment by FabienLelaquais** [comment] 2024-03-01 15:13
This would be a duplicate of #761.

**Closed as completed by FabienLelaquais** 2024-03-01 15:13 UTC
Labels: 📈 Improvement, 🖰 GUI
