### ISSUE TITLE
BUG- A broken link for the the ellipsis on the doc homepage

### ISSUE THREAD

**Issue by maxHeez** [Avaiga/taipy-doc#942] opened 2024-05-03 16:37 UTC
**Bug description**
A broken link for the the ellipsis on the [home page](https://docs.taipy.io/en/release-3.0/) of the documentation.

**Screenshots**
![image](https://github.com/Avaiga/taipy-doc/assets/168851136/e60cf0ec-ea8d-489b-8366-fdfeba630f93)

**Comment by FlorianJacta** [comment] 2024-05-06 08:21
Thank you for the issue. This is a duplicate of this issue so I will close this one to have a unique issue on this matter https://github.com/Avaiga/taipy-doc/issues/895

**Closed as completed by FlorianJacta** 2024-05-06 08:21 UTC
Labels: 💥Malfunction, 🟧 Priority: High
